sudo: required
services:
  - docker

before_install:
  - docker build -t snjanbu/multi-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true snjanbu/multi-client npm test

after_install:
  - docker run -t snjanbu/multi-client ./client
  - docker run -t snjanbu/multi-nginx ./nginx
  - docker run -t snjanbu/multi-server ./server
  - docker run -t snjanbu/multi-worker ./worker
  # Docker login
  - docker login -u="${DOCKER_ID}" -p="${DOCKER_PASSWORD}"
  # Push images to docker hub
  - docker push snjanbu/multi-client
  - docker push snjanbu/multi-nginx
  - docker push snjanbu/multi-server
  - docker push snjanbu/multi-worker