version: "3"
services:
  client:
    image: "snjanbu/multi-client"
    mem_limit: 128m
    host_name: "client"
  server:
    image: "snjanbu/multi-server"
    mem_limit: 128m
    host_name: "api"
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGHOST=$PGHOST
      - PGUSER=$PGUSER
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "snjanbu/multi-worker"
    mem_limit: 128m
    host_name: "worker"
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "snjanbu/multi-nginx"
    mem_limit: 128m
    host_name: "nginx"
    ports:
      - "80:80"
